version: '3.8'

services:
  documentserver:
    build:
      context: .
      dockerfile: Dockerfile.amd64
    container_name: onlyoffice-documentserver-intel
    network_mode: host
    environment:
      NODE_ENV: development-linux
      NODE_CONFIG_DIR: /app/Common/config
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: onlyoffice
      DB_USER: onlyoffice
      DB_PASS: onlyoffice
      RABBITMQ_HOST: localhost
      RABBITMQ_PORT: 5672
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    volumes:
      - ./App_Data:/app/App_Data
      - ./logs:/app/logs
    restart: unless-stopped

